# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 514)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.login_main = QtWidgets.QFrame(self.centralwidget)
        self.login_main.setGeometry(QtCore.QRect(0, 0, 541, 551))
        self.login_main.setStyleSheet("background-color:rgb(31, 31, 31)")
        self.login_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_main.setObjectName("login_main")
        self.login_buttons_holder = QtWidgets.QFrame(self.login_main)
        self.login_buttons_holder.setGeometry(QtCore.QRect(60, 40, 411, 421))
        self.login_buttons_holder.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(47, 47, 47)")
        self.login_buttons_holder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_buttons_holder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_buttons_holder.setObjectName("login_buttons_holder")
        self.transparent_effect_login = QtWidgets.QFrame(self.login_main)
        self.transparent_effect_login.setGeometry(QtCore.QRect(50, 30, 431, 441))
        self.transparent_effect_login.setStyleSheet("background-color:rgba(0,0,0,0.3);\n"
"border-radius:20px;")
        self.transparent_effect_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transparent_effect_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transparent_effect_login.setObjectName("transparent_effect_login")
        self.login_title = QtWidgets.QLabel(self.transparent_effect_login)
        self.login_title.setGeometry(QtCore.QRect(170, 100, 101, 51))
        self.login_title.setStyleSheet("color:rgb(255, 255, 255);\n"
"font-size:35px;\n"
"background-color:rgb(40. 40. 40)")
        self.login_title.setObjectName("login_title")
        self.login_btn_holder = QtWidgets.QFrame(self.transparent_effect_login)
        self.login_btn_holder.setGeometry(QtCore.QRect(60, 410, 331, 41))
        self.login_btn_holder.setStyleSheet("background-color:rgb(38, 38, 38)rgb(47, 47, 47);")
        self.login_btn_holder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_btn_holder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_btn_holder.setObjectName("login_btn_holder")
        self.username_Frame = QtWidgets.QFrame(self.transparent_effect_login)
        self.username_Frame.setGeometry(QtCore.QRect(20, 170, 381, 80))
        self.username_Frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(38, 38, 38)rgb(47, 47, 47);\n"
"}")
        self.username_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_Frame.setObjectName("username_Frame")
        self.Username = QtWidgets.QLineEdit(self.username_Frame)
        self.Username.setGeometry(QtCore.QRect(40, 30, 301, 21))
        self.Username.setStyleSheet("QLineEdit {\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"    font-size:15px;\n"
"}")
        self.Username.setInputMask("")
        self.Username.setText("")
        self.Username.setObjectName("Username")
        self.Username_label = QtWidgets.QLabel(self.username_Frame)
        self.Username_label.setGeometry(QtCore.QRect(30, 5, 111, 21))
        self.Username_label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font-size:15px;")
        self.Username_label.setObjectName("Username_label")
        self.password_Frame = QtWidgets.QFrame(self.transparent_effect_login)
        self.password_Frame.setGeometry(QtCore.QRect(20, 250, 381, 80))
        self.password_Frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(38, 38, 38)rgb(47, 47, 47);\n"
"}")
        self.password_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_Frame.setObjectName("password_Frame")
        self.Password = QtWidgets.QLineEdit(self.password_Frame)
        self.Password.setGeometry(QtCore.QRect(40, 30, 301, 21))
        self.Password.setStyleSheet("QLineEdit {\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"    font-size:15px;\n"
"}")
        self.Password.setInputMask("")
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.password_label = QtWidgets.QLabel(self.password_Frame)
        self.password_label.setGeometry(QtCore.QRect(30, 10, 111, 21))
        self.password_label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font-size:15px;")
        self.password_label.setObjectName("password_label")
        self.login_btn = QtWidgets.QPushButton(self.transparent_effect_login)
        self.login_btn.setGeometry(QtCore.QRect(70, 360, 301, 41))
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 33, 92);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"    font-size:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:red;\n"
"    border-radius:20px;\n"
"    background:#333\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.login_icon = QtWidgets.QToolButton(self.transparent_effect_login)
        self.login_icon.setGeometry(QtCore.QRect(165, 20, 91, 81))
        self.login_icon.setStyleSheet("QToolButton {\n"
"    background-color:rgb(255, 33, 92);\n"
"    border-radius:35px;\n"
"}")
        self.login_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":icons/login_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_icon.setIcon(icon)
        self.login_icon.setIconSize(QtCore.QSize(64, 64))
        self.login_icon.setObjectName("login_icon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UpLink"))
        self.login_title.setText(_translate("MainWindow", "Login"))
        self.Username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.Username_label.setText(_translate("MainWindow", "Username"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.login_btn.setText(_translate("MainWindow", "Login"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
